### ISSUE TITLE
Precompiled binaries for linux musl target

### ISSUE THREAD

**Issue by sambartik** [alexwlchan/dominant_colours#19]
If viable, it would be nice to have precompiled static binary (musl target) for Alpine.

**Comment by alexwlchan** [comment]
Sure. I use a GitHub Action to build the released versions, so I just had to add a couple of extra lines to the workflow.

There's an Alpine target in v1.1.6, and will be in all future versions also: https://github.com/alexwlchan/dominant_colours/releases/tag/v1.1.6

**Comment by sambartik** [comment]
That's awesome! Thanks!
